version: '3'

services:
  app:
    build: .
    # image: ubuntu:lastest
    ports:
      - '8080:3000'
    environment:
      - USER=robot
      - PASSWORD=robot
    volumes:
      - 'db-data:/usr/src/app/data'
volumes:
  db-data:
    driver: local
